[package]
name = "chord_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
serde = { version = "1.0", features = ["derive"] }
sha1 = "0.10.6"

[build-dependencies]
tonic-build = "0.12"
